### PR TITLE
add support for https_proxy

### PR DESCRIPTION
**Pull request by Flet**
Hello!

Thanks for putting together this neat package :)

This PR adds support for HTTPs proxies via the `https_proxy` environment variable. It uses [superagent-proxy](https://github.com/TooTallNate/superagent-proxy) to accomplish this.

Cheers!

### CODE REVIEW

**Comment by stewart** [comment]
Thanks for the PR!

Rather than an env var, I'd prefer if the configuration were inline, similarly to the existing `apod.apiKey` variable.

example usage:

``` javascript
var apod = require("apod");

apod.apiKey = "YOUR_API_KEY"
apod.proxy = "https://proxy.verysecure.com"

apod(function(err, data) {
});
```

I can just implement this myself, if you prefer.

**Comment by Flet** [comment]
Sure, its up to you. 

A lot of internet-enabled packages will look for `http_proxy` and `https_proxy` by default, so I was just trying to follow the same convention (the [request](https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables) package is a popular example).

**Comment by Flet** [comment]
Also put this together using your package: https://github.com/flet/spacewall :space_invader: 

Thanks again for making this :)

**Comment by stewart** [comment]
I'll merge then patch it to support both - preferring env var if available. Release should make it out sometime tonight. Thanks again!

**Comment by Flet** [comment]
Cool thanks!

**Comment by stewart** [comment]
Just published `apod@0.2.0` to NPM, should be good to go!

Added you to the `contributors` section of the `package.json`, hope you don't mind.

**Comment by Flet** [comment]
Ah, that's nice thanks :)

**Pull request merged**
